require_relative './data/hash/student_1_data'
require_relative './data/hash/student_4_data'
require_relative './data/hash/student_5_data'
require_relative './data/hash/student_6_data'
require_relative './data/hash/student_7_data'
require_relative './data/hash/student_95_data'
require_relative './data/hash/student_106_data'
require_relative './data/hash/student_240_data'
require_relative './data/hash/student_267_data'
require_relative './data/hash/student_268_data'
require_relative './data/hash/student_269_data'
require_relative './data/hash/student_270_data'
require_relative './data/hash/student_271_data'
require_relative './data/hash/student_95_details'
require_relative './data/hash/student_106_details'
require_relative './data/hash/student_106_flattened'
require_relative './data/hash/status_applied_page_1'
require_relative './data/hash/status_applied_page_2'
require_relative './data/hash/status_applied_page_3'
require_relative './data/hash/status_applied_pages_all'
require_relative './data/hash/status_applied_collected'
require_relative './data/hash/status_5_bad_records'
require_relative './data/hash/status_5_applied_records'
require_relative './data/hash/status_5_accepted_records'
require_relative './data/hash/status_5_enrolled_records'
require_relative './data/hash/status_applied_all_details'
require_relative './data/hash/status_applied_all_flattened'
require_relative './data/hash/status_applied_enrolled_flattened'
require_relative './data/hash/status_applied_all_flattened_multipayments'

module SpecData
  # puts "#{File.expand_path File.dirname(__FILE__)}"
end
